Modularize the type code from the main module
For some mysterious reason this fails to link correctly on my system.

The error occurs regardless of what I attempt to export from the
functions, so this is not anything specific that is wrong with my code.
It isn't due to all the type weirdness. Also, the linking works fine
when I compile outside of the stack ecosystem. So it must be something
wrong with stack. Deleting the .stack-work folder does not fix the
problem.

Here is the full error message:

```
/Users/zebulun.arendsee/src/git/safe-seqs/clean-seqs.cabal was generated with a newer version of hpack,
please upgrade and try again.
Building all executables for `clean-seqs' once. After a successful build of all of them, only specified executables will be rebuilt.
clean-seqs> configure (lib + exe)
Configuring clean-seqs-0.1.0.0...
clean-seqs> build (lib + exe)
Preprocessing library for clean-seqs-0.1.0.0..
Building library for clean-seqs-0.1.0.0..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules:
        TypeFoo
[1 of 3] Compiling Paths_clean_seqs [Optimisation flags changed]
[2 of 3] Compiling TypeFoo
[3 of 3] Compiling Lib
Preprocessing executable 'clean-seqs-exe' for clean-seqs-0.1.0.0..
Building executable 'clean-seqs-exe' for clean-seqs-0.1.0.0..
[1 of 2] Compiling Main [Optimisation flags changed]
[2 of 2] Compiling Paths_clean_seqs [Optimisation flags changed]
Linking .stack-work/dist/x86_64-osx/Cabal-3.2.1.0/build/clean-seqs-exe/clean-seqs-exe ...
Undefined symbols for architecture x86_64:
  "_cleanzmseqszm0zi1zi0zi0zm4J7KDpLATDtIA8kxXQcni3_TypeFoo_hLength_closure", referenced from:
      _Ls4tK_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Lu4G2_srt in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
  "_cleanzmseqszm0zi1zi0zi0zm4J7KDpLATDtIA8kxXQcni3_TypeFoo_zdfShowViewable_closure", referenced from:
      _Ls4vd_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Lu4Gk_srt in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
  "_cleanzmseqszm0zi1zi0zi0zm4J7KDpLATDtIA8kxXQcni3_TypeFoo_ZCzh_con_info", referenced from:
      _Ls4v8_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4uT_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4uE_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4up_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4ua_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4tU_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4tK_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      ...
  "_cleanzmseqszm0zi1zi0zi0zm4J7KDpLATDtIA8kxXQcni3_TypeFoo_label_closure", referenced from:
      _Ls4vK_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Lu4Gr_srt in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
  "_cleanzmseqszm0zi1zi0zi0zm4J7KDpLATDtIA8kxXQcni3_TypeFoo_releaseString_closure", referenced from:
      _Ls4vb_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Lu4Gj_srt in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
  "_cleanzmseqszm0zi1zi0zi0zm4J7KDpLATDtIA8kxXQcni3_TypeFoo_Viewable_con_info", referenced from:
      _Ls4vj_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
  "_cleanzmseqszm0zi1zi0zi0zm4J7KDpLATDtIA8kxXQcni3_TypeFoo_Number_con_info", referenced from:
      _Lc4yi_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4vH_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
  "_cleanzmseqszm0zi1zi0zi0zm4J7KDpLATDtIA8kxXQcni3_TypeFoo_zdfOrdHList0_closure", referenced from:
      _Lr4to_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Lu4wt_srt in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
  "_cleanzmseqszm0zi1zi0zi0zm4J7KDpLATDtIA8kxXQcni3_TypeFoo_HNil_con_info", referenced from:
      _Ls4v8_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4uT_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4uE_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4up_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4ua_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4tU_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4tK_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      ...
  "_cleanzmseqszm0zi1zi0zi0zm4J7KDpLATDtIA8kxXQcni3_TypeFoo_showType_closure", referenced from:
      _Ls4tz_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Lu4NH_srt in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
  "_cleanzmseqszm0zi1zi0zi0zm4J7KDpLATDtIA8kxXQcni3_TypeFoo_hetHead_closure", referenced from:
      _Ls4up_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Lu4Gc_srt in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
  "_cleanzmseqszm0zi1zi0zi0zm4J7KDpLATDtIA8kxXQcni3_TypeFoo_zdfShowHList_closure", referenced from:
      _Lr4ts_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4tX_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4tO_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Lu4wN_srt in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Lu4G5_srt in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Lu4G8_srt in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
  "_cleanzmseqszm0zi1zi0zi0zm4J7KDpLATDtIA8kxXQcni3_TypeFoo_zdfShowNumber_closure", referenced from:
      _Ls4vm_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Lu4Gn_srt in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
  "_cleanzmseqszm0zi1zi0zi0zm4J7KDpLATDtIA8kxXQcni3_TypeFoo_zdfOrdHList_closure", referenced from:
      _Lr4to_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4v8_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4uT_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Ls4uE_info in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Lu4wt_srt in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
      _Lu4Gg_srt in libHSclean-seqs-0.1.0.0-4J7KDpLATDtIA8kxXQcni3.a(Lib.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)

--  While building package clean-seqs-0.1.0.0 (scroll up to its section to see the error) using:
      /Users/zebulun.arendsee/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.2.1.0 build lib:clean-seqs exe:clean-seqs-exe --ghc-options
" -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

I'm running stack version 2.5.1.1 x86_64 on a macOS 10.14.6 and Apple
LLVM version 10.0.1 (clang-1001.0.46.4).